stages:
  - test
  - package
  - deploy

test_job_interpreter:
  stage: test
  image:
    name: amazon/aws-cli:latest
    entrypoint:  [ "/bin/bash"]
  script:
    - pip install -U -e  .
    - pip install -r requirements-test.txt
    - pytest --cov=deprecated -s -m 'not integration'

package_job_interpreter:
  stage: package
  image:
    name: amazon/aws-cli:latest
    entrypoint:  ["/bin/bash"]
  script:
    - pip install -U -e  .
    - pip install -r requirements-test.txt
    - python conftest.py build -vf && python conftest.py bdist_wheel
  artifacts:
    paths:
      - ./dist/*
      - ./main.py
    expire_in: 30 days

deploy_job_interpreter:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws s3 cp ./dist/ s3://job-interpreter/  --recursive
    - aws s3 cp ./main.py s3://job-interpreter/main.py
