name: ci

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: unit tests
        run: |
          pip install --upgrade pip
          pip install -U -e  .
          pip install -r requirements-test.txt
          pytest --cov=deprecated -s -m 'not integration'
      - name: build whl
        run: |
          python setup.py build -vf && python setup.py bdist_wheel
      - name: archive dist
        uses: actions/upload-artifact@v3
        with:
          name: dpp-dist
          retention-days: 30
          path: |
            ./dist/*
            ./main.py
