name: ci

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: unit tests
        run: |
          pip install --upgrade pip
          pip install -U -e  .
          pip install -r requirements-test.txt
          pytest --cov=deprecated -s -m 'not integration'
      - id: bump2version
        name: bump data product processor version to pre-release
        run: |
          pip install bump2version
          . ./version.sh
          echo "latest release: ${$VERSION}"
          head=$(git rev-parse --short HEAD)
          commits_since_tag=$(git rev-list ${VERSION}..HEAD --count)
          echo "new snapshot: ${VERSION}+${commits_since_tag}.${head}"
          bump2version --new-version ${VERSION}+${commits_since_tag}.${head} pre
      - name: build wheel
        run: |
          python setup.py build -vf && python setup.py bdist_wheel
      - name: archive dist
        uses: actions/upload-artifact@v3
        with:
          name: dpp-dist
          retention-days: 30
          path: |
            ./dist/*
            ./main.py
