# This is a basic workflow to help you get started with Actions

name: bump-version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build whl
        run: |
          python -m pip install --upgrade pip
          pip install -U -e  .
          pip install -r requirements-test.txt
          python setup.py build -vf && python setup.py bdist_wheel
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dpp-dist
          retention-days: 30
          path: |
            ./dist/*
            ./main.py
      - name: deploy to test pypi
        run: |
          pip install twine
          ls -alh
